version: '3.7'
services:
  mysqldb:
    image: mysql:8.0.31
    ports:
      - '3306:3306'
    volumes:
      - ./data-mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  node-app:
    build: ./gate-simulator
    ports:
      - '9999:9999'
