version: '3.7'
services:
  mysqldb:
    image: mysql:8.0.31
    ports:
      - '3306:3306'
    volumes:
      - ./data-mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
  node-app:
    build: ./gate-simulator
    ports:
      - '9999:9999'
